name: tamil-images-xyz

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
         node-version: '10.x'
    - name: install Gatsby CLi
      run: npm i -g gatsby-cli
    - name: Install packages via yarn and Build the Site
      env:
        GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
        GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
      run: |
        yarn
        yarn build
